version: "3"
services:
  client:
    build: "./client"
    container_name: "client"
    working_dir: "/app/src"
    ports:
      - "3000:3000"
  app:
    build: "./app"
    container_name: "app"
    working_dir: "/app/src"
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/app/src:/app/src"
    links:
      - "redis"
  redis:
    image: "redis:3"
    container_name: "redis"
