app:
  build: "./app"
  container_name: "app"
  working_dir: "/app/src"
  ports:
    - "8080:8080"
  volumes:
    - "$PWD/app/src:/app/src"
  links:
    - "redis"
redis:
  image: "redis:3"
  container_name: "redis"
